language: ruby
sudo: false
cache: bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
rvm:
  - '2.1.10'
  - '2.2.6'
  - '2.3.3'
  - jruby-9.1.7.0
matrix:
  include:
    - rvm: '2.4.0'
      gemfile: gemfiles/rails_head.gemfile
    - rvm: '2.3.3'
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: '2.4.0'
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 'jruby-9.1.7.0'
      gemfile: gemfiles/rails_5.0.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
